### ISSUE TITLE
Github Pages deploy link request

### ISSUE THREAD

**Issue by RichardVas** [Teaching-projects/SZE-MOSZE-2020-BruteForce#7]
Szeretném kérni a github pages beállítását a gh-pages branch root directory-ra.
@hegyhati

**Comment by hegyhati** [comment]
2+ napnyi keses, de beallitottam.

**Comment by vizvezetek** [comment]
@hegyhati Valami valószínűleg félre ment, mert nem megy. 
https://teaching-projects.github.io/SZE-MOSZE-2020-BruteForce/

**Comment by hegyhati** [comment]
Nem tudom, mi tortent, lehet elakadt a request valahol, passz. Most (megint) beallitottam. ha ok, zarjatok le.
